name: CI Build

on:
  push:
    branches: [ master ]
    tags:
    - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
#        - name: Ubuntu 22.04 x86_64
#          image: ghcr.io/muhkuh-sys/mbs_ubuntu_2204_x86_64:latest
#          distribution-id: ubuntu
#          distribution-version: "22.04"
#          cpu-architecture: x86_64
        - name: Ubuntu 22.04 arm64
          image: ghcr.io/muhkuh-sys/mbs_ubuntu_2204_x86_64:latest
          distribution-id: ubuntu
          distribution-version: "22.04"
          cpu-architecture: arm64
        - name: Ubuntu 22.04 riscv64
          image: ghcr.io/muhkuh-sys/mbs_ubuntu_2204_x86_64:latest
          distribution-id: ubuntu
          distribution-version: "22.04"
          cpu-architecture: riscv64
    container:
      image: ${{ matrix.platform.image }}
      options: --privileged
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Disable Git safe directory
      run: git config --system --add safe.directory '*'
    - name: Build
      run: ./build_artifact.py ${{ matrix.platform.distribution-id }} ${{ matrix.platform.distribution-version }} ${{ matrix.platform.cpu-architecture }}
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifacts_${{ matrix.platform.distribution-id }}_${{ matrix.platform.distribution-version }}_${{ matrix.platform.cpu-architecture }}
        path: build/repository
